-- Real notifications, generated by triggers on real events (new orders,
-- order status changes) rather than client-side inserts — a user shouldn't
-- be able to fabricate a notification for themself or anyone else.

create type notification_type as enum (
  'order_update', 'vendor_message', 'promotional', 'system', 'review', 'refund_update'
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type notification_type not null default 'system',
  title text not null,
  body text,
  link_url text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_id_created_at_idx on public.notifications (user_id, created_at desc);
create index notifications_user_id_unread_idx on public.notifications (user_id) where read_at is null;

alter table public.notifications enable row level security;

create policy "notifications_select_own" on public.notifications
  for select using (user_id = auth.uid());

create policy "notifications_update_own" on public.notifications
  for update using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "notifications_delete_own" on public.notifications
  for delete using (user_id = auth.uid());

-- No insert policy for anon/authenticated — rows are created exclusively by
-- the SECURITY DEFINER trigger functions below.

alter publication supabase_realtime add table public.notifications;

-- Notify the vendor as soon as one of their products is ordered.
create function public.notify_vendor_new_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, type, title, body, link_url)
  values (
    new.vendor_id,
    'order_update',
    'New order received',
    new.product_title_snapshot || ' × ' || new.quantity,
    '/vendor/orders'
  );
  return new;
end;
$$;

create trigger on_order_item_created_notify_vendor
  after insert on public.order_items
  for each row execute function public.notify_vendor_new_order();

-- Notify the customer whenever their order's status changes.
create function public.notify_customer_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_customer_id uuid;
begin
  select customer_id into target_customer_id from public.orders where id = new.order_id;

  if target_customer_id is not null then
    insert into public.notifications (user_id, type, title, body, link_url)
    values (
      target_customer_id,
      'order_update',
      'Order status updated',
      coalesce(new.note, 'Your order is now ' || new.status || '.'),
      '/account/orders'
    );
  end if;

  return new;
end;
$$;

create trigger on_order_status_history_notify_customer
  after insert on public.order_status_history
  for each row execute function public.notify_customer_order_status_change();
